//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kartoteka
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InterpolContext : DbContext
    {
        public InterpolContext()
            : base("name=InterpolContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Criminal> Criminals { get; set; }
        public virtual DbSet<Parameter> Parameters { get; set; }
        public virtual DbSet<Passport> Passports { get; set; }
        public virtual DbSet<Permit> Permits { get; set; }
        public virtual DbSet<Person> Persons { get; set; }
        public virtual DbSet<PSRelation> PSRelations { get; set; }
        public virtual DbSet<Spirit> Spirits { get; set; }
        public virtual DbSet<Syndicate> Syndicates { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
