//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kartoteka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passport
    {
        public int person_id { get; set; }
        public string person_citizenship { get; set; }
        public string person_nationality { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
