//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kartoteka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int person_id { get; set; }
        public string person_name { get; set; }
        public string person_nickname { get; set; }
        public string person_birthday { get; set; }
        public string photo_path { get; set; }
        public string person_status { get; set; }
    
        public virtual Criminal Criminal { get; set; }
        public virtual Parameter Parameter { get; set; }
        public virtual Passport Passport { get; set; }
        public virtual Permit Permit { get; set; }
        public virtual PSRelation PSRelation { get; set; }
        public virtual Spirit Spirit { get; set; }
    }
}
