//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kartoteka
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public decimal U_ID { get; set; }
        public string U_Name { get; set; }
        public Nullable<int> U_Age { get; set; }
    
        public virtual Password Password { get; set; }
    }
}
